<?php

	require_once __DIR__."/utils/BlockchainWallet.php";
	require_once __DIR__."/utils/CurlUtil.php";

	/**
	 * Public functions for other modules to use:
	 *
	 * blockchainaccounts_get_balance($denomination, $accountspec)
	 * blockchainaccounts_transaction($denomination, $from, $to, $amount, $label)
	 */

	/**
	 * Enable.
	 */
	function blockchainaccounts_enable() {
		//echo "enable module!!!\n";

		if (!field_info_field("field_blockchainaccounts_balance")) {
			$field=array(
				"field_name"=>"field_blockchainaccounts_balance",
				"type"=>"number_decimal",
			);

			field_create_field($field);
		}

		if (!field_info_instance("user","field_blockchainaccounts_balance","user")) {
			$instance=array(
				"field_name"=>"field_blockchainaccounts_balance",
				"entity_type"=>"user",
				"bundle"=>"user",
				"label"=>"Bitcoin Balance"
			);

			field_create_instance($instance);
		}

		if (!field_info_field("field_blockchainaccounts_address")) {
			$field=array(
				"field_name"=>"field_blockchainaccounts_address",
				"type"=>"text",
			);

			field_create_field($field);
		}

		if (!field_info_instance("user","field_blockchainaccounts_address","user")) {
			$instance=array(
				"field_name"=>"field_blockchainaccounts_address",
				"entity_type"=>"user",
				"bundle"=>"user",
				"label"=>"Bitcoin Address"
			);

			field_create_instance($instance);
		}

		if (!variable_get("blockchainaccounts_notification_key"))
			variable_set("blockchainaccounts_notification_key",md5(rand().microtime()));

		if (!variable_get("blockchainaccounts_required_confirmations"))
			variable_set("blockchainaccounts_required_confirmations",2);

		if (!db_table_exists("blockchainaccounts_transactions")) {
			db_create_table("blockchainaccounts_transactions",array(
				"description"=>"Transactions",
				"fields"=>array(
					"id"=>array("type"=>"serial","not null"=>"true"),
					"label"=>array("type"=>"varchar","length"=>255),
					"from_entity_type"=>array("type"=>"varchar","length"=>32),
					"from_entity_id"=>array("type"=>"int"),
					"from_balance"=>array("type"=>"int"),
					"to_entity_type"=>array("type"=>"varchar","length"=>32),
					"to_entity_id"=>array("type"=>"int"),
					"to_balance"=>array("type"=>"int"),
					"transaction_hash"=>array("type"=>"varchar","length"=>255),
					"target_address"=>array("type"=>"varchar","length"=>255),
					"confirmations"=>array("type"=>"int"),
					"amount"=>array("type"=>"int"),
					"state"=>array("type"=>"varchar","length"=>32),
					"timestamp"=>array("type"=>"int")
				),

				"indexes"=>array(
					"from"=>array("from_entity_type","from_entity_id"),
					"to"=>array("to_entity_type","to_entity_id"),
					"transaction_hash"=>array("transaction_hash"),
				),

				"primary key"=>array("id")
			));
		}
	}

	/**
	 * Field access.
	 * Don't allow direct access to the balance field.
	 */
	function blockchainaccounts_field_access($op, $field, $type, $entity) {
		if ($field["field_name"]=="field_blockchainaccounts_balance")
			return FALSE;

		if ($field["field_name"]=="field_blockchainaccounts_address")
			return FALSE;
	}

	/**
	 * Implements hook_menu().
	 *
	 * Advertise extra menu items and urls available.
	 */
	function blockchainaccounts_menu() {
		$items=array();

		// Account management pages on user profile.
		$items["user/%user/account"]=array(
			"title"=>t("Account"),
			"page callback"=>"blockchainaccounts_account_deposit",
			"page arguments"=>array(1),
			"access callback"=>TRUE,
			"type"=>MENU_LOCAL_TASK,
			"weight"=>1000
		);

		$items["user/%user/account/deposit"]=array(
			"title"=>t("Deposit"),
			"page callback"=>"blockchainaccounts_account_deposit",
			"page arguments"=>array(1),
			"access callback"=>TRUE,
			"type"=>MENU_DEFAULT_LOCAL_TASK,
			"weight"=>1
		);

		$items["user/%user/account/withdraw"]=array(
			"title"=>t("Withdraw"),
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("blockchainaccounts_account_withdraw_form"),
			"access callback"=>TRUE,
			"type"=>MENU_LOCAL_TASK,
			"weight"=>2
		);

		$items["user/%user/account/transfer"]=array(
			"title"=>t("Transfer"),
			"page callback"=>"drupal_get_form",
			"page arguments"=>array("blockchainaccounts_account_transfer_form"),
			"access callback"=>TRUE,
			"type"=>MENU_LOCAL_TASK,
			"weight"=>3
		);

		$items["user/%user/account/history"]=array(
			"title"=>t("History"),
			"page callback"=>"blockchainaccounts_account_history",
			"page arguments"=>array(1),
			"access callback"=>TRUE,
			"type"=>MENU_LOCAL_TASK,
			"weight"=>4
		);

		// Configuration section on the configuration page.
		$items['admin/config/blockchainaccounts']=array(
			'title' => 'blockchainaccounts',
			'description' => 'blockchainaccounts Configuration Section',
			'position' => 'right',
			'weight' => -100,
			'page callback' => 'system_admin_menu_block_page',
			'access arguments' => array('administer site configuration'),
			'file' => 'system.admin.inc',
			'file path' => drupal_get_path('module', 'system'),
		);

		// Configuration page, accessible both from the 
		// configuration and from the modules page. 
		$items["admin/modules/blockchainaccounts"] = $items['admin/config/blockchainaccounts/item'] = array(
			'title' => 'Blockchain Accounts',
			'description' => 'Blockchain Accounts Configuration',
			'page callback' => 'drupal_get_form',
			'access arguments' => array('access administration pages'),
			'page arguments' => array('blockchainaccounts_config_form'),
			'type'=>MENU_NORMAL_ITEM,
		);

		$items["blockchainaccounts/notification"]=array(
			"title"=>t("notifications"),
			"page callback"=>"blockchainaccounts_notification",
			"page arguments"=>array(1),
			"access callback"=>TRUE,
			"type"=>MENU_CALLBACK,
		);

		return $items;
	}

	/**
	 * Configuration form.
	 */
	function blockchainaccounts_config_form($form, &$form_state) {
		$form["blockchainaccounts_wallet_id"]=array(
			'#type' => 'textfield',
			'#title' => t('Wallet Id'),
			'#default_value' => variable_get('blockchainaccounts_wallet_id', ""),
			'#description' => t('Your wallet id at blockchain.info, or mocked url for testing.'),
		);

		$form["blockchainaccounts_wallet_password"]=array(
			'#type' => 'textfield',
			'#title' => t('Wallet Password'),
			'#default_value' => variable_get('blockchainaccounts_wallet_password', ""),
			'#description' => t('Your wallet password at blockchain.info.'),
		);

		$form["blockchainaccounts_notification_key"]=array(
			'#type' => 'textfield',
			'#title' => t('Notifications Key'),
			'#default_value' => variable_get('blockchainaccounts_notification_key'),
			'#description' => t('Key to accept for wallet notifications.'),
		);

		$notificationUrl=url("blockchainaccounts/notification",array(
			"absolute"=>TRUE,
			"query"=>array(
				"key"=>variable_get("blockchainaccounts_notification_key")
			)
		));

		$t=
			"<div class='form-item'>".
			"<b>Notification Url</b><br/>".
			"<input size='60' type='text' value='$notificationUrl' class='form-text' disabled/>".
			"<div class='description'>Configure blockchain.info to use this for wallet notifications</div>".
			"</div>";

		$form["notification_info"]=array(
			"#markup"=>$t
		);

		return system_settings_form($form);
	}

	/**
	 * Account history.
	 */
	function blockchainaccounts_account_history() {
		global $user;

		$content=blockchainaccounts_create_tab_content("History");

		$rows=array();

		$c1=db_and()->condition("from_entity_type","user")->condition("from_entity_id",$user->uid);
		$c2=db_and()->condition("to_entity_type","user")->condition("to_entity_id",$user->uid);
		$condition=db_or()->condition($c1)->condition($c2);

		$qrows=db_select("blockchainaccounts_transactions","t")
			->fields("t")
			->condition($condition)
			->orderBy("timestamp","DESC")
			->execute()
			->fetchAll(PDO::FETCH_ASSOC);

		foreach ($qrows as $qrow) {
			$label=$qrow["id"].". ".$qrow["label"];

			if ($qrow["target_address"]) {
				$url="https://blockchain.info/address/".$qrow["target_address"];
				$label.=", <a target='_blank' href='$url'>".mb_strimwidth($qrow["target_address"],0,8,"...")."</a>";
			}

			if ($qrow["transaction_hash"]) {
				$url="https://blockchain.info/tx/".$qrow["transaction_hash"];
				$label.=", <a target='_blank' href='$url'>".mb_strimwidth($qrow["transaction_hash"],0,8,"...")."</a>";
			}

			if ($qrow["state"]=="confirming") {
				$balance="N/A";
				$state=$qrow["state"].", ".$qrow["confirmations"]."/".variable_get("blockchainaccounts_required_confirmations");
			}

			else {
				$state=$qrow["state"];

				if ($qrow["to_entity_type"]=="user" && $qrow["to_entity_id"]==$user->uid)
					$balance=blockchainaccounts_from_satoshi("bits",$qrow["to_balance"])." bits";

				if ($qrow["from_entity_type"]=="user" && $qrow["from_entity_id"]==$user->uid)
					$balance=blockchainaccounts_from_satoshi("bits",$qrow["from_balance"])." bits";
			}

			if ($qrow["to_entity_type"]=="user" && $qrow["to_entity_id"]==$user->uid)
				$amount=blockchainaccounts_from_satoshi("bits",$qrow["amount"]);

			if ($qrow["from_entity_type"]=="user" && $qrow["from_entity_id"]==$user->uid)
				$amount=blockchainaccounts_from_satoshi("bits",-$qrow["amount"]);

			$rows[]=array(
				$label,
				format_date($qrow["timestamp"],"short"),
				$amount." bits",
				$balance,
				$state
			);
		}

		$content["history"]=array(
			'#theme' => 'table',
			'#header' => array(t('Transaction'), t('Time'), t('Amount'), t('Balance'), t('Status')),
			'#rows' => $rows
		);

		return $content;
	}

	/**
	 * Get wallet url.
	 */
	function blockchainaccounts_getBlockchainWallet() {
		static $wallet;

		if (!$wallet)
			$wallet=new BlockchainWallet(
				variable_get("blockchainaccounts_wallet_id"),
				variable_get("blockchainaccounts_wallet_password")
			);

		return $wallet;
	}

	/**
	 * Deposit to account.
	 */
	function blockchainaccounts_account_deposit() {
		global $user;

		$user_data=user_load($user->uid);

		if (!isset($user_data->field_blockchainaccounts_address[LANGUAGE_NONE][0]["value"])) {
			$wallet=blockchainaccounts_getBlockchainWallet();

			try {
				$address=$wallet->createNewAddress();
				$user_data->field_blockchainaccounts_address[LANGUAGE_NONE][0]["value"]=$address;
				field_attach_update("user",$user_data);
			}

			catch (Exception $e) {
				drupal_set_message(
					"Unable to create deposit address, try again later.<br/>".$e->getMessage(),
					"error");
			}
		}

		$content=blockchainaccounts_create_tab_content("Deposit");

		if (!isset($user_data->field_blockchainaccounts_address[LANGUAGE_NONE][0]["value"])) {
			$content["not_available"]=array(
				"#type"=>"markup",
				"#markup"=>"Deposits are not available at this time, please try again later."
			);

			return $content;
		}

		$address=$user_data->field_blockchainaccounts_address[LANGUAGE_NONE][0]["value"];
		$addressUrl="bitcoin://".$address;

		drupal_add_js(drupal_get_path("module","blockchainaccounts")."/jquery.qrcode-0.12.0.min.js");

		$content["container"]["deposit_address"]=array(
			"#type"=>"user_profile_item",
			"#title"=>"Deposit Address",
			"#markup"=>"<a href='$addressUrl'>$address</a>",
		);

		$vars=array(
			"text"=>$addressUrl
		);

		$templatePath=drupal_get_path("module","blockchainaccounts")."/depositaddress.tpl.php";
		$qrContent=theme_render_template($templatePath,$vars);

		$content["deposit_qrcode"]=array(
			"#markup"=>$qrContent,
		);

		$content["deposit_help"]=array(
			"#type"=>"markup",
			"#markup"=>
				"<br>Send bitcoins to the address above in order to fund your account.<br/>".
				"The funds will be available in your account after ".
				variable_get("blockchainaccounts_required_confirmations").
				" confirmations.<br/>".
				"Can check the progress of the confirmations on the account history page."
		);

		return $content;
	}

	/**
	 * Transfer from.
	 */
	function blockchainaccounts_account_transfer_form() {
		$form=blockchainaccounts_create_tab_content("Transfer");

		$form["username"]=array(
			"#type"=>"textfield",
			"#title"=>"User",
			"#description"=>"Enter the username of the user you want to transfer funds to.",
			"#required"=>TRUE
		);

		$form["amount"]=array(
			"#type"=>"textfield",
			"#title"=>"Amount",
			"#description"=>"Enter the amount in bits you want to transfer.",
			"#required"=>TRUE
		);

		$form["transfer_button"]=array(
			"#type"=>"submit",
			"#value"=>t("Transfer")
		);

		$form["#validate"]=array("blockchainaccounts_account_transfer_validate");
		$form["#submit"]=array("blockchainaccounts_account_transfer_submit");

		return $form;
	}

	/**
	 * Validate transfer.
	 */
	function blockchainaccounts_account_transfer_validate($form, &$form_state) {
		global $user;

		$value=$form["amount"]["#value"];
		$username=$form["username"]["#value"];

		if ($value>blockchainaccounts_get_balance("bits",array("uid"=>$user->uid)))
			form_set_error("amount","This amount is higher than your balance.");

		else if (!$value)
			form_set_error("amount","Please enter the amount in bits you want to withdraw.");

		$touser=user_load_by_name($username);
		if (!$touser) {
			$allow_transfer_to_node=TRUE;

			if ($allow_transfer_to_node && node_load_multiple(array(), array("title"=>$username)))
				drupal_set_message("That's a node");

			else
				form_set_error("username","User not found: ".$form["username"]["#value"]);
		}
	}

	/**
	 * Perform transfer.
	 */
	function blockchainaccounts_account_transfer_submit($form, &$form_state) {
		global $user;

		$amount=$form["amount"]["#value"];
		$username=$form["username"]["#value"];

		$touser=user_load_by_name($username);

		if ($touser) {
			$toaccount=array(
				"uid"=>$touser->uid
			);
		}

		else {
			$nodes=node_load_multiple(array(), array("title"=>$username));
			$node_id=array_keys($nodes)[0];

			if ($node_id) {
				$toaccount=array(
					"nid"=>$node_id
				);
			}
		}

		blockchainaccounts_transaction("bits",array("uid"=>$user->uid),$toaccount,$amount,"Local Transfer");

		drupal_set_message(
			"Your transfer to ".$username." of ".$amount." bits has been performed.\n".
			"Check account history page for details."
		);
	}

	/**
	 * Withdraw from account.
	 */
	function blockchainaccounts_account_withdraw_form() {
		$form=blockchainaccounts_create_tab_content("Withraw");

		$form["address"]=array(
			"#type"=>"textfield",
			"#title"=>"Address",
			"#description"=>"Enter the bitcoin address to withdraw to.",
			"#required"=>TRUE
		);

		$form["amount"]=array(
			"#type"=>"textfield",
			"#title"=>"Amount",
			"#description"=>"Enter the amount in bits you want to withdraw.",
			"#required"=>TRUE
		);

		$form["withdraw_button"]=array(
			"#type"=>"submit",
			"#value"=>t("Withdraw")
		);

		$form["#validate"]=array("blockchainaccounts_account_withdraw_validate");
		$form["#submit"]=array("blockchainaccounts_account_withdraw_submit");

		return $form;
	}

	/**
	 * Validate withdrawal request.
	 */
	function blockchainaccounts_account_withdraw_validate($form, &$form_state) {
		global $user;

		$value=$form["amount"]["#value"];

		if ($value>blockchainaccounts_get_balance("bits",array("uid"=>$user->uid)))
			form_set_error("amount","This amount is higher than your balance.");

		else if (!$value)
			form_set_error("amount","Please enter the amount in bits you want to withdraw.");
	}

	/**
	 * Process withdrawal request.
	 */
	function blockchainaccounts_account_withdraw_submit($form, &$form_state) {
		global $user;

		$amount=$form["amount"]["#value"];
		$balance=blockchainaccounts_change_balance("bits",array("uid"=>$user->uid),-$amount);

		db_insert("blockchainaccounts_transactions")
			->fields(array(
				"label"=>"Withdrawal",
				"from_entity_type"=>"user",
				"from_entity_id"=>$user->uid,
				"from_balance"=>blockchainaccounts_to_satoshi("bits",$balance),
				"amount"=>blockchainaccounts_to_satoshi("bits",$amount),
				"target_address"=>$form["address"]["#value"],
				"state"=>"scheduled",
				"timestamp"=>REQUEST_TIME
			))
			->execute();

		drupal_set_message(
			"Your withdrawal request has been received. ".
			"Check progress on your account history page."
		);
	}

	/**
	 * Perform and log transaction.
	 */
	function blockchainaccounts_transaction($denomination, $from, $to, $amount, $label) {
		if ($amount<0)
			throw new Exception("Can't make a transaction with negative amount");

		$from_balance=blockchainaccounts_get_balance($denomination,$from);
		$to_balance=blockchainaccounts_get_balance($denomination,$to);

		if ($amount>$from_balance)
			throw new Exception("Not enough balance, balance=".$from_balance);

		$from_balance=blockchainaccounts_change_balance($denomination, $from, -$amount);
		$to_balance=blockchainaccounts_change_balance($denomination, $to, $amount);

		$from_info=blockchainaccounts_expand_account_info($from);
		$to_info=blockchainaccounts_expand_account_info($to);

		$id=db_insert("blockchainaccounts_transactions")
			->fields(array(
				"label"=>$label,
				"from_entity_type"=>$from_info["entity_type"],
				"from_entity_id"=>$from_info["entity_id"],
				"from_balance"=>blockchainaccounts_to_satoshi($denomination,$from_balance),
				"to_entity_type"=>$to_info["entity_type"],
				"to_entity_id"=>$to_info["entity_id"],
				"to_balance"=>blockchainaccounts_to_satoshi($denomination,$to_balance),
				"amount"=>blockchainaccounts_to_satoshi($denomination,$amount),
				"state"=>"complete",
				"timestamp"=>REQUEST_TIME
			))
			->execute();

		if (!$id)
			throw new Exception("Unable to perform transaction");

		return $id;
	}

	/**
	 *
	 */
	function blockchainaccounts_expand_account_info($accountinfo) {
		if (isset($accountinfo["uid"]))
			return array(
				"uid"=>$accountinfo["uid"],
				"entity_type"=>"user",
				"entity_id"=>$accountinfo["uid"]
			);

		else if (isset($accountinfo["nid"]))
			return array(
				"nid"=>$accountinfo["nid"],
				"entity_type"=>"node",
				"entity_id"=>$accountinfo["nid"]
			);

		else
			throw new Exception("Unknown account");
	}

	/**
	 * Change the account balance.
	 */
	function blockchainaccounts_change_balance($denomination, $accountspec, $amount) {
		if (isset($accountspec["uid"])) {
			$users=entity_load("user",array($accountspec["uid"]));
			$user=$users[$accountspec["uid"]];

			if (!$user)
				throw new Exception("Unknown account.");

			$balance=0;

			if (isset($user->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"]))
				$balance=$user->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"];

			if ($amount<0 && -blockchainaccounts_to_satoshi($denomination,$amount)>$balance)
				throw new Exception("Not enough funds, balance=".$balance);

			$balance+=blockchainaccounts_to_satoshi($denomination,$amount);

			$user->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"]=$balance;
			field_attach_update("user",$user);

			return blockchainaccounts_from_satoshi($denomination,$balance);
		}

		else if (isset($accountspec["nid"])) {
			$nodes=entity_load("node",array($accountspec["nid"]));
			$node=$nodes[$accountspec["nid"]];

			if (!field_info_instance("node","field_blockchainaccounts_balance",$node->type)) {
				$instance=array(
					"field_name"=>"field_blockchainaccounts_balance",
					"entity_type"=>"node",
					"bundle"=>$node->type,
					"label"=>"Bitcoin Balance"
				);

				field_create_instance($instance);
			}

			$balance=0;

			if (isset($node->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"]))
				$balance=$node->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"];

			if ($amount<0 && -blockchainaccounts_to_satoshi($denomination,$amount)>$balance)
				throw new Exception("Not enough funds for node account, balance=".$balance);

			$balance+=blockchainaccounts_to_satoshi($denomination,$amount);

			$node->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"]=$balance;
			field_attach_update("node",$node);

			return blockchainaccounts_from_satoshi($denomination,$balance);
		}

		throw new Exception("Unknown account.");
	}

	/**
	 * Common things.
	 */
	function blockchainaccounts_create_tab_content($title) {
		global $user;

		$balance_str=blockchainaccounts_get_balance("bits",array("uid"=>$user->uid))." bits";

		$content=array(
			"container"=>array(
				"#type"=>"container",
				"#attributes"=>array(
					"class"=>array("profile")
				),

				"balance"=>array(
					"#type"=>"user_profile_item",
					"#title"=>"Current Balance",
					"#markup"=>$balance_str
				),

				"category"=>array(
					"#type"=>"user_profile_category",
					"#title"=>$title,
				),
			)
		);

		return $content;
	}

	/**
	 * Blockchain notification.
	 */
	function blockchainaccounts_notification() {
		if ($_REQUEST["key"]!=variable_get("blockchainaccounts_notification_key")) {
			watchdog("blockchainaccounts","Notification: Wrong key",array(),WATCHDOG_WARNING);
			exit();
		}

		$query = new EntityFieldQuery();
		$query->entityCondition('entity_type','user')
			->fieldCondition('field_blockchainaccounts_address','value',$_REQUEST["input_address"]);

		$result = $query->execute();
		$users_ids = array_keys($result['user']);		

		if (!$users_ids) {
			watchdog("blockchainaccounts","Notification: No matching user",array(),WATCHDOG_WARNING);
			exit();
		}

		$user_id=$users_ids[0];
		$transaction_hash=$_REQUEST["transaction_hash"];

		$transaction=db_select("blockchainaccounts_transactions","t")
			->fields("t")
			->condition("transaction_hash",$transaction_hash)
			->execute()
			->fetchAssoc();

		watchdog("blockchainaccounts","Current state: ".$transaction["state"]);

		if ($transaction && $transaction["state"]=="complete") {
			watchdog("blockchainaccounts","Notification: Already processed: ".$transaction_hash,array(),WATCHDOG_WARNING);

			echo "*ok*";
			return;
		}

		$confirmations=$_REQUEST["confirmations"];
		$value=$_REQUEST["value"];

		// Create or update the transaction.
		if ($transaction) {
			watchdog("blockchainaccounts","Notification: Updating: ".$transaction_hash);

			$res=db_update("blockchainaccounts_transactions")
				->fields(array(
					"confirmations"=>$confirmations
				))
				->condition("transaction_hash",$transaction_hash)
				->execute();

			if ($res!=1)
				watchdog("blockchainaccounts","Notification: expected one row, got: ".$res,array(),WATCHDOG_WARNING);
		}

		else {
			watchdog("blockchainaccounts","Notification: Creating: ".$transaction_hash);

			db_insert("blockchainaccounts_transactions")
				->fields(array(
					"label"=>"Deposit",
					"to_entity_type"=>"user",
					"to_entity_id"=>$user_id,
					"transaction_hash"=>$transaction_hash,
					"confirmations"=>$confirmations,
					"amount"=>$value,
					"state"=>"confirming",
					"timestamp"=>REQUEST_TIME
				))
				->execute();
		}

		// Confirm it, if enough confirmations.
		if ($confirmations>=variable_get("blockchainaccounts_required_confirmations")) {
			watchdog("blockchainaccounts","Notification: Completing: ".$transaction_hash);

			$users=entity_load("user",array($user_id));
			$user=$users[$user_id];

			$balance=0;

			if (isset($user->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"]))
				$balance=$user->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"];

			$balance+=$value;

			$user->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"]=$balance;
			field_attach_update("user",$user);

			$res=db_update("blockchainaccounts_transactions")
				->fields(array(
					"state"=>"complete",
					"timestamp"=>REQUEST_TIME,
					"to_balance"=>$balance
				))
				->condition("transaction_hash",$transaction_hash)
				->execute();

			echo "*ok*";
		}
	}

	/**
	 * Convert to satoshi.
	 */
	function blockchainaccounts_to_satoshi($denomination, $amount) {
		switch (strtolower($denomination)) {
			case "satoshi":
				return $amount;
				break;

			case "bits":
				return $amount*100;
				break;

			case "mbtc":
				return $amount*100000;
				break;

			case "btc":
				return $amount*100000000;
				break;

			default:
				throw new Exception("Unknown denomination: ".$denomination);
				return;
		}
	}

	/**
	 * Convert from satoshi.
	 */
	function blockchainaccounts_from_satoshi($denomination, $amount) {
		switch (strtolower($denomination)) {
			case "satoshi":
				return $amount;
				break;

			case "bits":
				return $amount/100;
				break;

			case "mbtc":
				return $amount/100000;
				break;

			case "btc":
				return $amount/100000000;
				break;

			default:
				throw new Exception("Unknown denomination: ".$denomination);
				return;
		}
	}

	/**
	 * Return the current balance of the specified account.
	 */
	function blockchainaccounts_get_balance($denomination, $accountspec) {
		if (isset($accountspec["uid"])) {
			$users=entity_load("user",array($accountspec["uid"]));
			$user=$users[$accountspec["uid"]];

			if (!$user)
				return FALSE;

			$balance=0;

			if (isset($user->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"]))
				$balance=$user->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"];

			return blockchainaccounts_from_satoshi($denomination,$balance);
		}

		else if (isset($accountspec["nid"])) {
			$nodes=entity_load("node",array($accountspec["nid"]));
			$node=$nodes[$accountspec["nid"]];

			if (!$node)
				return FALSE;

			$balance=0;

			if (isset($node->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"]))
				$balance=$node->field_blockchainaccounts_balance[LANGUAGE_NONE][0]["value"];

			return blockchainaccounts_from_satoshi($denomination,$balance);
		}

		else
			throw new Exception("Account not found");
	}
